name: navigation

publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^5.0.4

  core:
    path: ../core

  #Features
  favorites:
    path: ../features/favorites
  home:
    path: ../features/home
  splash:
    path: ../features/splash

dev_dependencies:
  flutter_lints: ^3.0.0

  auto_route_generator: 5.0.3
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
