name: home

publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  domain:
    path: ../../domain
  navigation:
    path: ../../navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
