name: core

publish_to: none

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0