name: domain

publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.9
  hive_generator: ^2.0.1