name: app_theme

publish_to: none

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/animations/splash_animation.json
    - assets/fonts/sora/
    - assets/icons/